### PR TITLE
Fix/keep existing wifi config

### LINKED ISSUE #10: Unable to turn off wifi AP mode on the gateway
Hi,

I use the ethernet link to connect the gateway to the internet. 

After activation the wifi AP mode is not turn off and my gateway always broadcast the SSID ""Things-Gateway-0001ECxxxxxx". The default password "thethings" also remain active... It's really not secure.

I'm unable to fix  this. I try the embedded web manager, the serial debug (the wifi cmd seem not work) and https://console.thethingsnetwork.org/gateways.

My firmware is :
(Firmware HASH (sha256)) 69 AE B7 78 1F 49 4E 7F BC B6 C7 CD 9C 59 4F 5D FA AA 3D 81 D4 9C 56 90 A6 83 81 98 FF 18 88 6A

Bootloader is:
Firmware name: AmazingAckermann, type: 0, version: 1.0.0, commit: 917719b9, timestamp: 1498499973
Bootloader revision: 1, commit: 7167873a, timestamp: 1496411298
Build time: Jun 26 2017 19:59:53

### LINKED ISSUE #33: Gateway losing client connection to AP, defaulting back to Things-Gateway-xxx
I've deployed a new gateway and configured the device for my local WiFi.  This works as expected for a while, then drops connection to WiFi until manually power cycled.  I've connected a UART to collect debug logs which show the device assigning itself IP 192.168.84.1 and starting the AP when this happens which is the default behavior when it cannot connect to the assigned AP but otherwise working as expected. 

For testing purposes I enabled beta firmware updates, which ran, and which haven't changed the resulting behavior.  When I connect to the Things-Gateway-xxx and watch the logs, I can see it directly stating that it's keeping the AP configured due to a client being connected (`INET: Not trying to connect to WiFi router again because client is connected (after 120 seconds)`).  When I disconnect my client from that AP, that message does not appear again, but it still drops off of the assigned SSID and defaults back to acting as an AP (again, without mentioning a client being connected).

I have recorded logs from the original firmware (factory? - I don't see where to collect the firmware details), then showing the upgrade to beta, showing one instance of a client being connected to the AP, and a whole lot of failing to connect to the assigned AP.  When you see "10.0.100.20", that's the gateway connecting successfully to my internal network.

## To recap:

- Environment has 3 APs, good signal strength and channel separation
- TTN Gateway will connect to the assigned SSID immediately without problem
- Some time later, it will drop that connection and go into AP mode with no obvious reason given as to why
- No clients are connected to the Things-Gateway-xxx AP

I am working on a city-wide deployment of these devices.  This is the first device to be tested and right now we are at a hard stop with this deployment until this issue can be resolved.

### PR DESCRIPTION
**Pull request by KrishnaIyer**
Copy of commit message:
```
The previous WiFi patch that restricted AP mode to only when there is no WiFi config causes issues with gateways with exisiting WiFi config.
Though the two are not directly related, the patch seems to have uncovered an existing problem.
In the current code, the WiFi ping timeout is 8s (4x2 tries). But practically, it takes 10-15s to re-connect. So, after 8s, we go to WAIT_FOR_NETWORK state where the WiFi module is restarted.
This causes a loop since everytime the pings timeout at 8s and restart the WiFi module.
By increasing the ping timeout to a higher value of 120s (60x2 tries), this issue is not observed since the WiFi connects after roughly after 15-20s.

This issue was not observed in gateways where the WiFi config was erased since the initial wait for connection already takes into account the extra time needed to establish a connection.

Two things to be considered in the future
- Select an appropriate value for the timeout based on testing instead an arbitirarily chosen value.
- Solve the actual problem of the WiFi driver (which is beyond the scope of the Application code)
```

Together with #26 this fixes #33, fixes #10 and may be related to #8 and #24

### CODE REVIEW

**Comment by htdvisser** [comment]
So the only actual change here, was to change the PING_TIMEOUT?

Removing `wifiConnectStartTick` seems unrelated, but if it wasn't used, then I think it's fine to clean it up.

**Comment by KrishnaIyer** [comment]
Yes `PING_TIMEOUT` was the only change. The variable was unnecessary and in the same context so I removed it.

**Comment by martinichka** [comment]
@KrishnaIyer have you tested it with a router without internet (so it will receive DHCP but ping will fail) and then recover internet? Does it recover the connection?

**Comment by KrishnaIyer** [comment]
@martinichka : I'll test that today and let you know.

**Comment by KrishnaIyer** [comment]
@martinichka : I tested this and the connection recovers. 
Procedure
- Unplug the input to router while the gateway is connected to the WiFi.
- Ping Timeout after 120s
- Plugin the router input. 
- Gateway reconnects and sends MQTT status messages.

**Pull request merged**
